### Numpy

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.21.5


In [3]:
data=np.array([450,650,782,856,452,365,400,500,656])

In [4]:
type(data)

numpy.ndarray

In [5]:
data.ndim

1

In [9]:
data=np.array([[784,78569],[850,568956],[400,85746]])

In [10]:
data

array([[   784,  78569],
       [   850, 568956],
       [   400,  85746]])

In [11]:
data.ndim

2

In [12]:
data.shape

(3, 2)

In [14]:
data.dtype

dtype('int64')

In [15]:
data.astype('float')

array([[7.84000e+02, 7.85690e+04],
       [8.50000e+02, 5.68956e+05],
       [4.00000e+02, 8.57460e+04]])

In [17]:
!pip install cv2

ERROR: Could not find a version that satisfies the requirement cv2 (from versions: none)
ERROR: No matching distribution found for cv2


In [18]:
!pip install opencv-python

     |████████████████████████████████| 46.4 MB 1.2 MB/s eta 0:00:012


In [19]:
data=np.array([[784,78569],[850,568956],[400,85746]])

In [20]:
data[0,:]

array([  784, 78569])

In [21]:
data[:,1]

array([ 78569, 568956,  85746])

In [23]:
data[0,0]

784

In [24]:
data[2,1]

85746

In [26]:
import pandas as pd

In [27]:
df=pd.DataFrame(data)

In [28]:
df

0       1
0  784   78569
1  850  568956
2  400   85746

In [30]:
dfsum=df.sum(axis=1)

In [31]:
dfsum

0     79353
1    569806
2     86146
dtype: int64

In [32]:
import cv2

In [34]:
#img=cv2.imread("")

In [35]:
df.mean(axis=1)

0     39676.5
1    284903.0
2     43073.0
dtype: float64

In [36]:
df.sum(axis=1)

0     79353
1    569806
2     86146
dtype: int64

In [37]:
data.max(axis=0)

array([   850, 568956])

In [38]:
data.max(axis=1)

array([ 78569, 568956,  85746])

In [39]:
data

array([[   784,  78569],
       [   850, 568956],
       [   400,  85746]])

In [40]:
data.shape

(3, 2)

In [41]:
data.reshape(2,3)

array([[   784,  78569,    850],
       [568956,    400,  85746]])

In [42]:
data.reshape(1,6)

array([[   784,  78569,    850, 568956,    400,  85746]])

In [43]:
data

array([[   784,  78569],
       [   850, 568956],
       [   400,  85746]])

In [44]:
np.resize(data,(3,3))

array([[   784,  78569,    850],
       [568956,    400,  85746],
       [   784,  78569,    850]])

In [46]:
data.flatten()

array([   784,  78569,    850, 568956,    400,  85746])

In [47]:
data.tolist()

[[784, 78569], [850, 568956], [400, 85746]]

In [48]:
np.random.randint(45, size=(4,4))

array([[10, 13, 13,  0],
       [14, 35, 43, 32],
       [14, 17, 18, 38],
       [42, 32, 43, 42]])

In [50]:
np.random.rand(5)

array([0.10260353, 0.56241526, 0.25649767, 0.32810502, 0.9750885 ])

In [51]:
np.random.rand(4,4)

array([[0.38172235, 0.7819191 , 0.7521502 , 0.91221315],
       [0.52709582, 0.79170061, 0.48295136, 0.08672396],
       [0.75522317, 0.41492002, 0.25535804, 0.86941789],
       [0.82219432, 0.12787155, 0.43392798, 0.41256209]])

In [56]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [57]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [58]:
data1=np.array([[574546,543435,677688],[79325,68593,6975],[152,534,2766]])

In [59]:
data1

array([[574546, 543435, 677688],
       [ 79325,  68593,   6975],
       [   152,    534,   2766]])

In [72]:
data1.shape

(3, 3)

In [61]:
data1.size

9

In [62]:
data1.dtype

dtype('int64')

In [76]:
data1.reshape(1,9)

array([[574546, 543435, 677688,  79325,  68593,   6975,    152,    534,
          2766]])

In [64]:
np.resize(data1,(4,4))

array([[574546, 543435, 677688,  79325],
       [ 68593,   6975,    152,    534],
       [  2766, 574546, 543435, 677688],
       [ 79325,  68593,   6975,    152]])

In [65]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [67]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [68]:
data1.sum()

1954014

In [77]:
data1.sum(axis=1)

array([1795669,  154893,    3452])

In [78]:
data1.sum(axis=0)

array([654023, 612562, 687429])

In [79]:
data1.mean()

217112.66666666666

In [81]:
data1.std()

273150.061597406

In [82]:
data1.var()

74610956150.66667

In [83]:
data1.max()

677688

In [84]:
data1.min()

152

In [86]:
np.random.rand(5,5)

array([[0.68498312, 0.59683738, 0.77739472, 0.74604503, 0.74830859],
       [0.70711103, 0.26639973, 0.59445695, 0.43983872, 0.95823002],
       [0.87774441, 0.44850908, 0.02393911, 0.18170305, 0.298568  ],
       [0.68786022, 0.46607601, 0.85179893, 0.80989628, 0.30758764],
       [0.61563607, 0.80102419, 0.21949888, 0.177268  , 0.98386118]])

In [89]:
np.random.randint(200, size=(5,5))

array([[ 52, 116, 191, 185,  46],
       [ 53, 142, 166,  36,  27],
       [ 58,  56, 140, 132,  71],
       [ 82, 121, 141,  74, 185],
       [181,  26, 103,  26, 101]])

In [90]:
data1.flatten()

array([574546, 543435, 677688,  79325,  68593,   6975,    152,    534,
         2766])

In [91]:
data1.tolist()

[[574546, 543435, 677688], [79325, 68593, 6975], [152, 534, 2766]]

In [93]:
a=np.linspace(0,50,10)

In [94]:
a

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [95]:
a.size

10

In [98]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [99]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [100]:
data.T

array([[   784,    850,    400],
       [ 78569, 568956,  85746]])

In [101]:
data+5

array([[   789,  78574],
       [   855, 568961],
       [   405,  85751]])

In [102]:
np.add(data[:,0],10)

array([794, 860, 410])

In [103]:
data[:,0]=np.add(data[:,0],10)

In [104]:
df=data.copy()

In [105]:
df

array([[   794,  78569],
       [   860, 568956],
       [   410,  85746]])

In [106]:
np.delete(df,1,axis=0)

array([[  794, 78569],
       [  410, 85746]])

In [107]:
df.sum(axis=1)

array([ 79363, 569816,  86156])

In [108]:
np.sin(data)

array([[ 0.73314932, -0.78909012],
       [-0.71483427,  0.84365997],
       [ 0.99975451, -0.58905351]])

In [109]:
np.log(data)

array([[ 6.67708346, 11.2717325 ],
       [ 6.75693239, 13.25155838],
       [ 6.01615716, 11.35914472]])

In [110]:
np.abs(data)

array([[   794,  78569],
       [   860, 568956],
       [   410,  85746]])

In [111]:
out=np.sqrt(data)

In [112]:
out

array([[ 28.17800561, 280.30162326],
       [ 29.3257566 , 754.29172076],
       [ 20.24845673, 292.82417933]])

In [113]:
np.ceil(out)

array([[ 29., 281.],
       [ 30., 755.],
       [ 21., 293.]])

In [114]:
np.round(out)

array([[ 28., 280.],
       [ 29., 754.],
       [ 20., 293.]])

In [115]:
np.power(data,2)

array([[      630436,   6173087761],
       [      739600, 323710929936],
       [      168100,   7352376516]])